from enum import Enum


class AppRoute(str, Enum):
    TEXT_BOX = "./text-box"
    CHECKBOX = "./checkbox"
    RADIO_BUTTON = "./radio-button"
    WEBTABLES = "./webtables"
    BUTTONS = "./buttons"
    LINKS = "./links"
    BROKEN_LINKS = "./broken"
    UPLOAD_DOWNLOAD = "./upload-download"
    DYNAMIC_PROPERTIES = "./dynamic-properties"
    PRACTICE_FORM = "./automation-practice-form"
    BROWSER_WINDOWS = "./browser-windows"
    ALERTS = "./alerts"
    FRAMES = "./frames"
    NESTED_FRAMES = "./nestedframes"
    MODAL_DIALOGS = "./modal-dialogs"
    ACCORDIAN = "./accordian"
    DATE_PICKER = "./date-picker"
    SLIDER = "./slider"
    PROGRESS_BAR = "./progress-bar"
    TABS = "./tabs"
    TOOL_TIPS = "./tool-tips"
    MENU = "./menu"
    SELECT_MENU = "./select-menu"
    SORTABLE = "./sortable"
    SELECTABLE = "./selectable"
    RESIZABLE = "./resizable"
    DROPPABLE = "./droppable"
    DRAGABBLE = "./dragabble"
